version: '3.1'

services:
  recipe_db:
    container_name: mysql
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: KLEINANZEIGEN
      MYSQL_ROOT_PASSWORD: start01
    ports:
      - 4406:3306
    volumes:
      - kleinanzeigen:/var/lib/mysql
  hs-kleinanzeigen-cache:
    container_name: hs-kleinanzeigen-cache
    image: redis:7.0.12
    ports:
      - 127.0.0.1:6379:6379
volumes:
  kleinanzeigen:
