version: '3.1'

services:
  recipe_db:
    container_name: mysql
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: KLEINANZEIGEN
      MYSQL_ROOT_PASSWORD: start01
    ports:
      - 4406:3306
    volumes:
      - kleinanzeigen:/var/lib/mysql
volumes:
  kleinanzeigen:
