server:
  port: 8081
  servlet:
    context-path: /hs-kleinanzeigen

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/KLEINANZEIGEN?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: start01


# use the following properties to execute DDL on startup
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 600000


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

