server:
  port: 8081
# FIXME: adjust context-path to set base url of application
  servlet:
    context-path: /hs-kleinanzeigen

spring:
# FIXME: use the following credentials for your sql connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/KLEINANZEIGEN?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: start01

# use the following properties to execute DDL on startup
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# FIXME: use the following properties to enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  
