-- Drop the tables if they exist to start fresh
DROP TABLE IF EXISTS NOTEPAD;
DROP TABLE IF EXISTS AD;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS USER;

-- Create the CATEGORY table
CREATE TABLE CATEGORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

-- Create the USER table
CREATE TABLE USER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PHONE VARCHAR(20),
    LOCATION VARCHAR(255),
    CREATED TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create the AD table
CREATE TABLE AD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE ENUM('OFFER', 'REQUEST') NOT NULL,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE INT,
    LOCATION VARCHAR(255),
    CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

-- Create the NOTEPAD table
CREATE TABLE NOTEPAD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    AD_ID INT NOT NULL,
    NOTE VARCHAR(255),
    CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (AD_ID) REFERENCES AD(ID)
);