

-- Drop the tables if they exist to start fresh
DROP TABLE IF EXISTS AD;
DROP TABLE IF EXISTS CATEGORY;

-- Create the CATEGORY table
CREATE TABLE CATEGORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

-- Create the AD table
CREATE TABLE AD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE ENUM('OFFER', 'REQUEST') NOT NULL,
    CATEGORY_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE INT,
    LOCATION VARCHAR(255),
    CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);